############################
## Author
############################

author:
  name: mattiasaxell
  image: author.png
  greeting: "Mattias Axell's Linktree site :tada:"
  icon: ":tea:"

############################
## Links
############################

links:
  - github: https://github.com/mattiasaxell
  - gitlab: https://gitlab.com/mattiasaxell
  - website: https://mattiasaxell.com/
  - x-twitter: https://x.com/mattiasaxell
  - mastodon: https://mastodon.acc.sunet.se/@mattiasaxell
  - linkedin: https://www.linkedin.com/in/mattiasaxell
  # - instagram:
  # - reddit:
  # - telegram:
  # - whatsapp:
  # - signal:
  # - codepen:
  # - dev:
  - email: mailto:hi@mattiasaxell.com
  # - discord:
  - orcid: https://orcid.org/0009-0003-4300-1927
  # - slack:
  # - stack-overflow:
  # - twitch:
  # - patreon:
  # - soundcloud:
  # - dribbble:
  # - stack-exchange:
  # - tiktok:
  # - youtube:
  # - keybase:
  # - flickr:
  # - tumblr:
  # - kickstarter:
  # - snapchat:
  # - bluesky:
  # - bitbucket:
  # - bandcamp:
  # - etsy:
  # - spotify:
  # - pinterest:
  # - strava:
  # - untappd:
  # - skype:
  # - medium:
  # - foursquare:
  # - apple:
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

##############################
## Monochromatic color scheme
##############################

# all links will be slate-700 (or slate-50 in dark mode)
# https://tailwindcss.com/docs/customizing-colors
monochrome: true

############################
## Colunms of Links
############################

# between 2 & 6 columns are supported (both incl)
columns: 2

###########################
## Icon text
###########################

# add the icon name to each icon
icontext: true

############################
## Tooltips
############################

# add tooltips on all icons
tooltip: false

###############################
## OpenGraph & Twitter Cards
###############################

title: Mattias Axell Linktree
description: "Linktree website for Mattias Axell"
images:
  - thumbnail.png
